"""Targeted semantic checks on the highest-risk emitter paths.

Tier 1 asserts a migration *executes* (D38). These few tests go one step further and
assert it did the right thing -- but only on the specific constructs where "executed
successfully" and "behaves correctly" can plausibly diverge:

  * an identity/auto-increment column that runs but never generates a value
  * a partial index emitted without its predicate, silently covering every row
  * a prefix index whose length was dropped, silently indexing the whole column
  * a cast that succeeds on an empty table and fails on a populated one

These are deliberately narrow. They are not general introspection -- that remains
deferred -- and they are chosen because each one would otherwise pass tier 1 while
producing a database that enforces something different from what was asked for.

Every information_schema lookup binds its values as parameters rather than formatting
them into the SQL.
"""
import pytest

from schemavcs.dialects import emit
from schemavcs.engine.plan import plan
from schemavcs.model import schema

pytestmark = pytest.mark.engine

LOSSY_OK = dict(acknowledge_lossy=True)
EMPTY = schema().build()


def seed(db, snap):
    db.apply(emit(plan(EMPTY, snap, **LOSSY_OK), db.dialect))


def test_an_identity_column_actually_generates_values(db):
    """`GENERATED BY DEFAULT AS IDENTITY` and `AUTO_INCREMENT` both execute happily
    when emitted wrongly -- the failure only shows up on the first insert."""
    base = (schema().table("t").col("id", "bigint", pk=True, autoincrement=True)
            .col("n", "varchar(20)").build())
    seed(db, base)

    db.execute("INSERT INTO t (n) VALUES ('a')")
    db.execute("INSERT INTO t (n) VALUES ('b')")
    ids = sorted(r[0] for r in db.query("SELECT id FROM t"))

    assert len(ids) == 2 and ids[0] != ids[1], "identity must produce distinct values"
    assert all(i is not None for i in ids)


def test_a_cast_requiring_retype_works_on_a_populated_table(db):
    """A retype on an empty table proves nothing: the engine has no rows to convert.
    This one has data, which is where a missing USING clause actually bites."""
    base = schema().table("t").col("id", "bigint", pk=True).col("v", "text").build()
    seed(db, base)
    db.execute("INSERT INTO t (id, v) VALUES (1, '42')")

    db.apply(emit(plan(base, base.evolve().retype_col("t.v", "int").build(),
                       **LOSSY_OK), db.dialect))

    assert db.query("SELECT v FROM t")[0][0] == 42


def test_a_partial_index_keeps_its_predicate(db):
    """Emitting a partial index without its WHERE clause executes fine and produces
    an index that covers every row -- a database that looks right and is not."""
    if db.dialect != "postgres":
        pytest.skip("MySQL has no partial indexes; the emitter refuses instead")
    base = schema().table("t").col("id", "bigint", pk=True).col("c", "int").build()
    target = base.evolve().add_index("t", "i_p", ["c"], where="c > 5").build()
    seed(db, base)

    db.apply(emit(plan(base, target), "postgres"))

    definition = db.query(
        "SELECT indexdef FROM pg_indexes WHERE indexname = %s", ("i_p",))[0][0]
    assert "WHERE" in definition.upper(), f"predicate was lost: {definition}"


def test_a_prefix_index_keeps_its_length(db):
    """MySQL records the prefix in `SUB_PART`. Losing it silently indexes the whole
    column, which changes both the size and the behaviour of the index."""
    if db.dialect != "mysql":
        pytest.skip("Postgres has no prefix indexes; the emitter refuses instead")
    from schemavcs.model.evolve import IndexSpec

    base = schema().table("t").col("id", "bigint", pk=True).col("c", "text").build()
    target = base.evolve().add_index(
        "t", "i_pref", [IndexSpec(column="c", prefix_length=12)]).build()
    seed(db, base)

    db.apply(emit(plan(base, target), "mysql"))

    rows = db.query(
        "SELECT SUB_PART FROM information_schema.STATISTICS "
        "WHERE TABLE_SCHEMA = DATABASE() AND INDEX_NAME = %s", ("i_pref",))
    assert rows and rows[0][0] == 12, f"prefix length lost: {rows}"


def test_a_unique_constraint_is_actually_enforced(db):
    """A UNIQUE that emits but does not enforce is worse than no constraint at all,
    because the schema claims a guarantee the data does not have."""
    base = (schema().table("t").col("id", "bigint", pk=True)
            .col("e", "varchar(50)", nullable=False).unique("uq_e", ["e"]).build())
    seed(db, base)
    db.execute("INSERT INTO t (id, e) VALUES (1, 'x')")

    with pytest.raises(Exception):
        db.execute("INSERT INTO t (id, e) VALUES (2, 'x')")


def test_a_foreign_key_is_actually_enforced(db):
    base = (schema().table("p").col("id", "bigint", pk=True)
            .table("c").col("id", "bigint", pk=True).col("p_id", "bigint")
            .fk("fk_p", ["p_id"], "p", ["id"]).build())
    seed(db, base)

    with pytest.raises(Exception):
        db.execute("INSERT INTO c (id, p_id) VALUES (1, 999)")


def test_a_check_constraint_is_actually_enforced(db):
    base = (schema().table("t").col("id", "bigint", pk=True).col("qty", "int")
            .check("ck_qty", "qty >= 0").build())
    seed(db, base)
    db.execute("INSERT INTO t (id, qty) VALUES (1, 5)")

    with pytest.raises(Exception):
        db.execute("INSERT INTO t (id, qty) VALUES (2, -1)")


def test_a_rename_swap_leaves_the_data_in_the_right_columns(db):
    """The temp-name detour must move NAMES, not data. If the plan accidentally
    copied values, this is where it shows."""
    base = (schema().table("t").col("id", "bigint", pk=True)
            .col("x", "int").col("y", "int").build())
    seed(db, base)
    db.execute("INSERT INTO t (id, x, y) VALUES (1, 10, 20)")
    target = (base.evolve().rename_col("t.x", "__s").rename_col("t.y", "x")
              .rename_col("t.__s", "y").build())

    db.apply(emit(plan(base, target), db.dialect))

    x, y = db.query("SELECT x, y FROM t")[0]
    assert (x, y) == (20, 10), "the values must follow their original columns"
