"""Operation -> SQL, both dialects (E-01..E-10, E-80..E-83).

These tests are about *text*, and deliberately about the places where the two engines
disagree rather than about every character of every statement. Asserting on whole SQL
strings makes tests that break on whitespace and pass on semantics, which is exactly
backwards. The strings are verified for real in the live-execution suite; here the
subject is divergence.
"""
import pytest

from schemavcs.dialects import UnrepresentableError, emit
from schemavcs.engine.plan import plan
from schemavcs.model import schema

BOTH = ["postgres", "mysql"]
LOSSY_OK = dict(acknowledge_lossy=True)


def sql_for(base, target, dialect, **kw):
    return emit(plan(base, target, **kw), dialect).text()


def only_statement(base, target, dialect, **kw):
    script = emit(plan(base, target, **kw), dialect)
    assert len(script) == 1, script.statements
    return script.statements[0]


# ================================================================== happy path
def test_E01_create_table_covers_every_supported_construct():
    base = schema().build()
    target = (schema().table("t")
              .col("id", "bigint", pk=True, autoincrement=True)
              .col("name", "varchar(100)", nullable=False)
              .col("note", "text", default="''")
              .unique("uq_name", ["name"])
              .check("ck_note", "note <> ''")
              .build())

    pg = sql_for(base, target, "postgres")

    assert 'CREATE TABLE "t"' in pg
    assert '"id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY' in pg
    assert '"name" varchar(100) NOT NULL' in pg
    assert """"note" text DEFAULT ''""" in pg
    assert 'CONSTRAINT "pk_t" PRIMARY KEY ("id")' in pg
    assert 'CONSTRAINT "uq_name" UNIQUE ("name")' in pg
    assert """CONSTRAINT "ck_note" CHECK (note <> '')""" in pg


def test_E01b_mysql_uses_its_own_identifiers_and_identity_syntax():
    base = schema().build()
    target = schema().table("t").col("id", "bigint", pk=True,
                                     autoincrement=True).build()

    my = sql_for(base, target, "mysql")

    assert "CREATE TABLE `t`" in my
    assert "`id` bigint NOT NULL AUTO_INCREMENT" in my


@pytest.mark.parametrize("dialect", BOTH)
def test_E02_drop_table(base_schema, dialect):
    target = base_schema.evolve().drop_table("users").build()

    stmt = only_statement(base_schema, target, dialect, **LOSSY_OK)

    assert stmt.startswith("DROP TABLE") and "users" in stmt


@pytest.mark.parametrize("dialect", BOTH)
def test_E03_add_and_drop_column(base_schema, dialect):
    added = base_schema.evolve().add_col("users", "age", "int").build()
    assert "ADD COLUMN" in only_statement(base_schema, added, dialect)

    dropped = base_schema.evolve().drop_col("users.email").build()
    assert "DROP COLUMN" in only_statement(base_schema, dropped, dialect, **LOSSY_OK)


@pytest.mark.parametrize("dialect", BOTH)
def test_E04_rename_column(base_schema, dialect):
    target = base_schema.evolve().rename_col("users.email", "contact").build()

    stmt = only_statement(base_schema, target, dialect)

    assert "RENAME COLUMN" in stmt
    assert "email" in stmt and "contact" in stmt


def test_E05_retype_diverges_postgres_alters_mysql_redefines(base_schema):
    """The divergence most likely to be got wrong.

    MySQL `MODIFY COLUMN` is a full redefinition: any clause left out is *discarded*.
    Emitting `MODIFY email varchar(500)` for a NOT NULL column would silently drop
    the NOT NULL. Postgres `ALTER COLUMN ... TYPE` touches only the type.
    """
    target = base_schema.evolve().retype_col("users.email", "varchar(500)").build()

    pg = only_statement(base_schema, target, "postgres")
    my = only_statement(base_schema, target, "mysql")

    assert 'ALTER COLUMN "email" TYPE varchar(500)' in pg
    assert "NOT NULL" not in pg, "Postgres must not restate unrelated attributes"

    assert "MODIFY COLUMN `email` varchar(500) NOT NULL" in my, \
        "MySQL must restate NOT NULL or it is silently dropped"


def test_E05b_postgres_adds_a_using_clause_only_when_a_cast_is_needed(base_schema):
    base = base_schema.evolve().add_col("users", "c", "int").build()

    needs_cast = base.evolve().retype_col("users.c", "text").build()
    assert "USING" in only_statement(base, needs_cast, "postgres")

    implicit = base.evolve().retype_col("users.c", "bigint").build()
    assert "USING" not in only_statement(base, implicit, "postgres")


def test_E06_set_and_drop_not_null(base_schema):
    loosened = base_schema.evolve().set_nullable("users.email", True).build()
    assert "DROP NOT NULL" in only_statement(base_schema, loosened, "postgres")
    assert "MODIFY COLUMN" in only_statement(base_schema, loosened, "mysql")

    base = base_schema.evolve().add_col("users", "n", "int").build()
    tightened = base.evolve().set_nullable("users.n", False).build()
    assert "SET NOT NULL" in only_statement(base, tightened, "postgres", **LOSSY_OK)


@pytest.mark.parametrize("dialect", BOTH)
def test_E07_set_and_drop_default(base_schema, dialect):
    with_default = base_schema.evolve().set_default("users.email", "'x'").build()
    assert "SET DEFAULT 'x'" in only_statement(base_schema, with_default, dialect)

    without = with_default.evolve().set_default("users.email", None).build()
    assert "DROP DEFAULT" in only_statement(with_default, without, dialect)


@pytest.mark.parametrize("dialect", BOTH)
def test_E08_add_each_constraint_kind(base_schema, dialect):
    uniq = base_schema.evolve().add_unique("users", "uq", ["email"]).build()
    assert "ADD CONSTRAINT" in only_statement(base_schema, uniq, dialect)
    assert "UNIQUE" in only_statement(base_schema, uniq, dialect)

    chk = base_schema.evolve().add_check("users", "ck", "email <> ''").build()
    assert "CHECK" in only_statement(base_schema, chk, dialect)


def test_E08b_dropping_a_foreign_key_diverges(two_tables):
    """MySQL needs the constraint kind; the generic form only works on 8.0.19+."""
    target = two_tables.evolve().drop_constraint("orders.fk_orders_user").build()

    assert "DROP CONSTRAINT" in only_statement(two_tables, target, "postgres")
    assert "DROP FOREIGN KEY" in only_statement(two_tables, target, "mysql")


def test_E09_create_and_drop_index_live_in_different_namespaces(base_schema):
    with_idx = base_schema.evolve().add_index("users", "idx", ["email"]).build()
    assert "CREATE INDEX" in only_statement(base_schema, with_idx, "postgres")

    dropped = with_idx.evolve().drop_index("users.idx").build()
    assert only_statement(with_idx, dropped, "postgres") == 'DROP INDEX "idx";'
    assert "ALTER TABLE `users` DROP INDEX" in only_statement(with_idx, dropped,
                                                             "mysql")


@pytest.mark.parametrize("dialect", BOTH)
def test_E10_rename_table(base_schema, dialect):
    target = base_schema.evolve().rename_table("users", "accounts").build()

    stmt = only_statement(base_schema, target, dialect)

    assert "RENAME TO" in stmt and "accounts" in stmt


# ============================================================ engine honesty (E-80+)
def test_E80_a_postgres_script_is_wrapped_in_one_transaction(base_schema):
    target = base_schema.evolve().add_col("users", "a", "int").build()

    script = emit(plan(base_schema, target), "postgres")

    assert script.transactional
    assert script.text().startswith("BEGIN;")
    assert script.text().rstrip().endswith("COMMIT;")


def test_E81_a_mysql_script_is_NOT_wrapped(base_schema):
    """Not an omission. MySQL commits each DDL statement implicitly, so a BEGIN
    would imply a rollback guarantee the engine does not provide (D18)."""
    target = base_schema.evolve().add_col("users", "a", "int").build()

    script = emit(plan(base_schema, target), "mysql")

    assert not script.transactional
    assert "BEGIN" not in script.text()
    assert "COMMIT" not in script.text()


def test_E82_a_mysql_script_carries_a_no_rollback_marker(base_schema):
    target = base_schema.evolve().drop_col("users.email").build()

    text = emit(plan(base_schema, target, **LOSSY_OK), "mysql").text()

    assert "NO ROLLBACK" in text


def test_E83_the_marker_sits_at_the_FIRST_irreversible_step(base_schema):
    """One marker at the boundary is actionable: everything above it is recoverable.
    A marker on every destructive line is noise that stops being read."""
    base = (base_schema.evolve().add_col("users", "a", "int")
            .add_col("users", "b", "int").build())
    target = (base.evolve().add_col("users", "safe_one", "text")
              .drop_col("users.a").drop_col("users.b").build())

    script = emit(plan(base, target, **LOSSY_OK), "mysql")

    marked = [i for i, s in enumerate(script.steps) if s.note
              and "NO ROLLBACK" in s.note]
    assert len(marked) == 1, "exactly one marker"
    irreversible = [i for i, s in enumerate(script.steps) if s.irreversible]
    assert marked[0] == min(irreversible)
    assert script.steps[marked[0]].sql.startswith("ALTER TABLE `users` DROP COLUMN")


def test_postgres_does_not_carry_a_no_rollback_marker(base_schema):
    """Because it can roll back. Emitting the warning anyway would train people to
    ignore it."""
    target = base_schema.evolve().drop_col("users.email").build()

    text = emit(plan(base_schema, target, **LOSSY_OK), "postgres").text()

    assert "NO ROLLBACK" not in text


# ============================================================== honest refusals
def test_a_partial_index_is_refused_for_mysql_not_silently_widened(base_schema):
    """Emitting a non-partial index would produce a database that looks right and
    enforces something different -- the worst available outcome."""
    target = base_schema.evolve().add_index("users", "idx", ["email"],
                                            where="email IS NOT NULL").build()

    p = plan(base_schema, target)
    emit(p, "postgres")                       # fine

    with pytest.raises(UnrepresentableError) as e:
        emit(p, "mysql")
    assert "partial index" in str(e.value)
    assert "every row" in str(e.value), "the message must say what would go wrong"


def test_an_unsigned_column_is_refused_for_postgres(base_schema):
    from schemavcs.model.types import ColumnType
    from dataclasses import replace as dc_replace

    t = base_schema.table("users")
    col = dc_replace(t.column("id"), type=ColumnType("int", (), unsigned=True))
    target = dc_replace(base_schema, tables=(dc_replace(
        t, columns=tuple(col if c.id == col.id else c for c in t.columns)),))

    p = plan(base_schema, target, **LOSSY_OK)
    emit(p, "mysql")                          # fine

    with pytest.raises(UnrepresentableError, match="unsigned"):
        emit(p, "postgres")


def test_a_mysql_prefix_index_is_refused_for_postgres(base_schema):
    from schemavcs.model.evolve import IndexSpec

    target = base_schema.evolve().add_index(
        "users", "idx", [IndexSpec(column="email", prefix_length=10)]).build()

    p = plan(base_schema, target)
    emit(p, "mysql")                          # fine

    with pytest.raises(UnrepresentableError, match="prefix"):
        emit(p, "postgres")


def test_an_unknown_dialect_is_refused_with_the_options_listed(base_schema):
    target = base_schema.evolve().add_col("users", "a", "int").build()

    with pytest.raises(ValueError, match="no emitter"):
        emit(plan(base_schema, target), "oracle")


def test_a_temp_name_step_is_annotated_as_machinery(base_schema):
    """Generated DDL is read by humans. An unexplained `__schemavcs_tmp_1` in a
    migration is alarming; a comment saying why it is there is not."""
    base = (base_schema.evolve().add_col("users", "x", "int")
            .add_col("users", "y", "int").build())
    target = (base.evolve().rename_col("users.x", "__s")
              .rename_col("users.y", "x").rename_col("users.__s", "y").build())

    script = emit(plan(base, target), "postgres")

    noted = [s for s in script.steps if s.note and "temporary name" in s.note]
    assert len(noted) == 2


def test_mysql_refuses_to_index_a_text_column_without_a_prefix_length(base_schema):
    """Discovered by applying generated DDL to a real MySQL server (D38).

    MySQL stores TEXT/BLOB out of line and cannot index it without being told how many
    leading bytes to use. The emitter previously produced `ADD CONSTRAINT ... UNIQUE
    (note)` and the server rejected it -- valid-looking SQL that fails at execution,
    which is exactly the class of bug string assertions cannot catch.
    """
    base = base_schema.evolve().add_col("users", "note", "text").build()
    target = base.evolve().add_index("users", "idx_note", ["note"]).build()

    p = plan(base, target)
    emit(p, "postgres")                        # Postgres indexes TEXT fine

    with pytest.raises(UnrepresentableError) as e:
        emit(p, "mysql")
    assert "prefix length" in str(e.value)
    assert "VARCHAR(n)" in str(e.value), "the message must name a way forward"


def test_mysql_accepts_a_text_index_when_a_prefix_length_is_given(base_schema):
    from schemavcs.model.evolve import IndexSpec

    base = base_schema.evolve().add_col("users", "note", "text").build()
    target = base.evolve().add_index(
        "users", "idx_note", [IndexSpec(column="note", prefix_length=32)]).build()

    stmt = only_statement(base, target, "mysql")

    assert "`note`(32)" in stmt


def test_mysql_refuses_a_unique_constraint_over_a_text_column(base_schema):
    base = base_schema.evolve().add_col("users", "note", "text").build()
    target = base.evolve().add_unique("users", "uq_note", ["note"]).build()

    with pytest.raises(UnrepresentableError, match="TEXT"):
        emit(plan(base, target), "mysql")


# ------------------------------------------------------------------ D48: unknown types
def test_E90_an_unknown_type_is_refused_rather_than_passed_through(base_schema):
    """The model is permissive about type names on purpose (D6) and knows nothing about
    dialects (D5), so a typo reaches the emitter intact. Before this, `TYPES.get(base,
    base)` passed it through and produced `ALTER COLUMN "x" TYPE somethign` -- DDL that
    parses here and fails on the server, which is the failure mode D39 exists to prevent.
    """
    from schemavcs.dialects import emit
    from schemavcs.engine.plan import plan
    from schemavcs.dialects.emit import UnrepresentableError

    target = base_schema.evolve().retype_col("users.email", "somethign").build()

    with pytest.raises(UnrepresentableError) as e:
        emit(plan(base_schema, target, acknowledge_lossy=True), "postgres")

    assert "somethign" in str(e.value)
    assert "varchar" in str(e.value), "the message must list what IS available"


@pytest.mark.parametrize("dialect,type_name", [
    ("postgres", "blob"),      # MySQL has it, Postgres does not
    ("mysql", "jsonb"),        # and the other way round
    ("mysql", "uuid"),
])
def test_E91_a_type_one_engine_lacks_is_refused_for_that_engine(base_schema, dialect,
                                                               type_name):
    """Not every unknown type is a typo. Some are real types the *other* engine has,
    which is the case most likely to bite: the schema was authored against Postgres and
    someone asks for MySQL."""
    from schemavcs.dialects import emit
    from schemavcs.engine.plan import plan
    from schemavcs.dialects.emit import UnrepresentableError

    target = base_schema.evolve().retype_col("users.email", type_name).build()
    p = plan(base_schema, target, acknowledge_lossy=True)

    with pytest.raises(UnrepresentableError, match=type_name):
        emit(p, dialect)


def test_E92_mysql_refuses_an_unbounded_varchar(base_schema):
    """Postgres reads a bare `varchar` as unbounded and MySQL rejects the statement, so
    a schema authored on one and emitted for the other produced DDL that would not run.
    Same family as E-90: the neutral model can hold it, this engine cannot express it.
    """
    from schemavcs.dialects import emit
    from schemavcs.dialects.emit import UnrepresentableError
    from schemavcs.engine.plan import plan

    target = base_schema.evolve().retype_col("users.email", "varchar").build()
    p = plan(base_schema, target, acknowledge_lossy=True)

    emit(p, "postgres")                       # legal there, and stays legal

    with pytest.raises(UnrepresentableError, match="unbounded"):
        emit(p, "mysql")
